### ISSUE TITLE
음악 MOCK 데이터 전달 요청

### ISSUE THREAD

**Issue by seoyoonyi** [MelodyMate/melodymate-front#3]
# Description
플레이어 기능 구현을 하기 위해서 음악 MOCK 데이터가 필요합니다.

## Todo
- [ ]  음악 MOCK 데이터 전달

**Comment by andeok** [comment]
notion -> MOCK Data 문서 추가 완료 했어요.
https://www.notion.so/seoyoonyi/MOCK-Data-e32a4beb79c14966bbc2043b7cc3047b?pvs=4
